services:
  # Web Service - The main Flask application
  - type: web
    name: zonarcom
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: zoonarcom@gmail.com
      - key: MAIL_PASSWORD
        value: vnmlzqhuvwktbucj
      - key: MAIL_DEFAULT_SENDER
        value: zoonarcom@gmail.com
      - key: RENDER
        value: true
    region: frankfurt
    plan: free
    healthCheckPath: /health
    disk:
      name: database-backup
      mountPath: /opt/render/project/src/backup
      sizeGB: 1

# Add a cron job for automatic price checking
cron:
  - name: price-tracker-job
    schedule: "0 */6 * * *" # Run every 6 hours
    command: python price_checker.py
    envVars:
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: zoonarcom@gmail.com
      - key: MAIL_PASSWORD
        value: vnmlzqhuvwktbucj
      - key: MAIL_DEFAULT_SENDER
        value: zoonarcom@gmail.com
      - key: RENDER
        value: true
      - key: SECRET_KEY
        fromService:
          name: zonarcom
          type: web
          envVarKey: SECRET_KEY
      - key: SUPABASE_URL
        fromService:
          name: zonarcom
          type: web
          envVarKey: SUPABASE_URL
      - key: SUPABASE_KEY
        fromService:
          name: zonarcom
          type: web
          envVarKey: SUPABASE_KEY
      - key: SUPABASE_SERVICE_KEY
        fromService:
          name: zonarcom
          type: web
          envVarKey: SUPABASE_SERVICE_KEY 