services:
  - type: web
    name: zonar
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    # Specify disk storage and RAM
    disk:
      name: zonar-data
      mountPath: /data
      sizeGB: 1
    plan: free 