services:
  # Web Service - The main Flask application
  - type: web
    name: zonar
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER
        value: true
      - key: SECRET_KEY
        sync: false  # Secret value set via Render dashboard
      - key: MAIL_USERNAME
        sync: false  # Secret value set via Render dashboard
      - key: MAIL_PASSWORD
        sync: false  # Secret value set via Render dashboard
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: SUPABASE_URL
        sync: false  # Secret value set via Render dashboard
      - key: SUPABASE_KEY
        sync: false  # Secret value set via Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Secret value set via Render dashboard
    disk:
      name: database-backup
      mountPath: /opt/render/project/src/.backup
      sizeGB: 1

# Add a cron job for automatic price checking
cron:
  - name: price-tracker-job
    schedule: "0 */6 * * *" # Run every 6 hours
    command: python price_checker.py
    envVars:
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: zoonarcom@gmail.com
      - key: MAIL_PASSWORD
        value: vnmlzqhuvwktbucj
      - key: MAIL_DEFAULT_SENDER
        value: zoonarcom@gmail.com
      - key: RENDER
        value: true
      - key: SECRET_KEY
        fromService:
          name: zonar-amazon-tracker
          type: web
          envVarKey: SECRET_KEY
      - key: SUPABASE_URL
        fromService:
          name: zonar-amazon-tracker
          type: web
          envVarKey: SUPABASE_URL
      - key: SUPABASE_KEY
        fromService:
          name: zonar-amazon-tracker
          type: web
          envVarKey: SUPABASE_KEY
      - key: SUPABASE_SERVICE_KEY
        fromService:
          name: zonar-amazon-tracker
          type: web
          envVarKey: SUPABASE_SERVICE_KEY 