"""Add firebase_uid to User model

Revision ID: 552961c7e03a
Revises: 9fc474d0c01c
Create Date: 2025-04-03 17:02:10.356124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552961c7e03a'
down_revision = '9fc474d0c01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_reset_token'), ['reset_token'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_google_id'), ['google_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_verification_token'), ['verification_token'])
        batch_op.drop_column('verification_token_expiry')
        batch_op.drop_column('reset_token_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_verification_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_reset_token'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.alter_column('language',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('firebase_uid')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('google_id')
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
