"""Add is_admin field to User model

Revision ID: 9fc474d0c01c
Revises: 38f4d4f24aa1
Create Date: 2025-04-03 04:03:35.781784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc474d0c01c'
down_revision = '38f4d4f24aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
